<?php

namespace Bot\User\Infrastructure\Providers;

use Bot\User\Domain\Repositories\UserRepository;
use Bot\User\Infrastructure\Repositories\UserEloquentRepository;
use Laracord\LaracordServiceProvider;

class UserServiceProvider extends LaracordServiceProvider
{
    public function register(): void
    {
        app()->bind(UserRepository::class, UserEloquentRepository::class);
    }

    public function boot(): void
    {
        // TODO: Change the autogenerated stub
    }
}
